services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $dataDirectory: "%kimai.data_dir%"

    KimaiPlugin\ChromePluginBundle\:
        resource: '../../*'
        exclude: '../../{Resources}'

    KimaiPlugin\ChromePluginBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
        public: true

    KimaiPlugin\ChromePluginBundle\Twig\:
        resource: '../../Twig'
        tags: ['twig.extension']
