services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $dataDirectory: "%kimai.data_dir%"

    KimaiPlugin\TrelloBundle\:
        resource: '../../*'
        exclude: '../../{Resources}'

    KimaiPlugin\TrelloBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
        public: true

    KimaiPlugin\TrelloBundle\Service\:
        resource: '../../Service'
        public: true
                
#    KimaiPlugin\ChromePluginBundle\Repository\ExtProjectRepository:
#        class:     Doctrine\ORM\EntityRepository
#        factory:   ['@doctrine.orm.entity_manager', getRepository]
#        arguments: ['KimaiPlugin\ChromeExtBundle\Entity\ExtProject']
        