version: '3.5'
services:

    # Apache with sqlite, the dev/evaluate option
    kimai:
        image: kimai/kimai2:apache-debian-1.8-dev
        environment:
            - APP_ENV=prod
            - TRUSTED_HOSTS=localhost,tobias.neontribe.co.uk,home.batch.org.uk,192.168.51.191,trello.batch.org.uk
            - ADMINMAIL=admin@kimai.local
            - ADMINPASS=av1Ndsy64TaB4yc5y7FFbFhJ
        ports:
            - 8001:8001
        volumes:
            - ./php.ini-development:/usr/local/etc/php/php.ini
            - ./plugins:/opt/kimai/var/plugins
            - ./security.yaml:/opt/kimai/config/packages/security.yaml
        restart: unless-stopped
        healthcheck:
            test: curl -s -o /dev/null http://localhost:8001 || exit 1
            interval: 20s
            # start_period: 10s
            timeout: 10s
            retries: 3
        logging:
            driver: "json-file"
            options:
                max-size: "10k"
                max-file: "10"

    web:        image: nginx:alpine
        volumes:
            - ./nginx_site.conf:/etc/nginx/conf.d/default.conf
            - ./letsencrypt:/etc/letsencrypt
        ports:
            - 443:443
            - 80:80
        restart: always
        healthcheck:
            test:  wget --spider https://nginx/health || exit 1
            interval: 20s
            # start_period: 10s
            timeout: 10s
            retries: 3
        logging:
            driver: "json-file"
            options:
                max-size: "10k"
                max-file: "10"

