version: '3.5'
services:

    # Apache with sqlite, the dev/evaluate option
    kimai:
        image: kimai/kimai2:fpm-alpine-1.8-dev
        environment:
            - APP_ENV=dev
            - TRUSTED_HOSTS=localhost,tobias.neontribe.co.uk
            - ADMINMAIL=admin@kimai.local
            - ADMINPASS=changemeplease
        volumes:
            - fpm-kimai:/opt/kimai
            - ./php.ini-development:/usr/local/etc/php/php.ini
            - ./plugins:/opt/kimai/var/plugins
        ports:
            - 8001:8001
        restart: unless-stopped
        healthcheck:
            test: curl -s -o /dev/null http://localhost:8001 || exit 1
            interval: 20s
            # start_period: 10s
            timeout: 10s
            retries: 3

    nginx:
        image: nginx:alpine
        ports:
            - 8002:80
            - 8443:443
        volumes:
            - ./nginx_site.conf:/etc/nginx/conf.d/default.conf
            - /etc/letsencrypt:/etc/letsencrypt/
            - fpm-kimai:/opt/kimai
        restart: unless-stopped
        depends_on:
            - kimai
        healthcheck:
            test:  wget --spider https://nginx/health || exit 1
            interval: 20s
            # start_period: 10s
            timeout: 10s
            retries: 3

volumes:
    fpm-kimai:
