services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $dataDirectory: "%kimai.data_dir%"

    KimaiPlugin\TrelloBundle\:
        resource: '../../*'
        exclude: '../../{Resources}'

    KimaiPlugin\TrelloBundle\Controller\:
       resource: '../../Controller'
       tags: ['controller.service_arguments']

        # KimaiPlugin\DemoBundle\Configuration\DemoConfiguration:
        # arguments:
        # $settings: '%demo_settings%'
