nelmio_api_doc:
    models:
        names:
            - { alias: DemoForm,        type: KimaiPlugin\DemoBundle\Form\DemoType,        groups: [Default, Entity, Demo] }
            - { alias: DemoEntity,      type: KimaiPlugin\DemoBundle\Entity\DemoEntity,    groups: [Default, Entity, Demo] }
            - { alias: DemoCollection,  type: KimaiPlugin\DemoBundle\Entity\DemoEntity,    groups: [Default, Collection, Demo] }
